### ISSUE TITLE
[Idea]: Colored tablist

### ISSUE THREAD

**Issue by davidegrigioni** [98ping/Alchemist#12]
### Describe the feature

Could you add a Feature like that?

![image](https://user-images.githubusercontent.com/65981549/220782717-84bc8864-d19e-448f-b709-f5e6076a3f6e.png)

with a colored tablist per rank for example HELPER nickname colored in the tablist as green

### How is the feature useful to all Alchemist users?

I think it could be a cool feature as you don't need to install other plugins

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by Nopock** [comment]
I believe this is better implemented per server as its too general of a feature but it can easily be achieved using Alchemist placeholders + the `Tab` plugin

**Comment by 98ping** [comment]
To add on to Nopox's comment, we also do not want to implement a tablist plugin-side because by default it would force our plugin to override and other tablist out there and that would not be good for most users because they have their own configured system in place.
