### ISSUE TITLE
[Bug]: Player dosen't get disconnected after being banned.

### ISSUE THREAD

**Issue by vezzzz** [98ping/Alchemist#13]
###  Alchemist Version

Spigot Version

### Server logs

https://paste.gg/p/anonymous/a621e024923b44a397481cc80a41b0c4

### Server Version

```shell
This server is running CraftBukkit version git-Spigot-21fe707-741a1bd (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
```

### Bug Description

When using /ban it doesn't disconnect the victim after the use of the command. The Victim can log out but cannot rejoin since they are banned.

### Steps to reproduce

get two accounts
ban the one account with the other
/ban (user) (reason)
![image](https://user-images.githubusercontent.com/111653051/230502427-106b39f2-a349-4427-b4e6-bc64c59115f9.png)
(This shows on the banned user's screen)

### Agreements

- [X] I have searched for and ensured there isn't already an open or resolved issue(s) regarding this.
- [X] I was able to reproduce my issue on a freshly setup and up-to-date server with the latest version of  Alchemist  with no other plugins and with no kinds of other server or client mods.

**Comment by 98ping** [comment]
https://github.com/98ping/Alchemist/releases/tag/2.03
