### ISSUE TITLE
[Idea]: 

### ISSUE THREAD

**Issue by xyz-lang** [98ping/Alchemist#5]
### Describe the feature

I hope alchemist can implement random teleport feature, and importing ranks from other rank cores.

### How is the feature useful to all Alchemist users?

Some people like myself already use another rank core like aquacore so it would be great for my players if I can just import ranks. TYSM BEST FREE RANK CORE 

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by 98ping** [comment]
I already have a plugin that is kind of like that with staffmode and essential things so cross-contaminating them is pretty irrelivant.

But I could very easily add aquacore support which was something I was going to do anyway to allow for compatability

**Comment by Nopock** [comment]
> I already have a plugin that is kind of like that with staffmode and essential things so cross-contaminating them is pretty irrelivant.
> 
> But I could very easily add aquacore support which was something I was going to do anyway to allow for compatability

How would aquacore support work? Would alchemist disable its features or just hook into aquacore for punishments, grants, ranks ect?

**Comment by 98ping** [comment]
I would get the data from aquacore and then convert it into the data thats in alchemist using conversion methods

**Comment by xyz-lang** [comment]
Can you make XeBasic ty
