### ISSUE TITLE
[Idea]: Module

### ISSUE THREAD

**Issue by Nopock** [98ping/Alchemist#6]
### Describe the feature

It would be a nice feature to have to ability to disable certain things.

One of the nice things about aquacore is you can config pretty much everything.

It would be nice for stuff like friends, parties to be modular.

### How is the feature useful to all Alchemist users?

It would allow users to disable certain things.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by Nopock** [comment]
Also I would recommend contacting BennyDoesStuff#2003 on discord to try and get alchemist on minehut (Provide better descriptions and maybe your disc inside the config)

**Comment by 98ping** [comment]
will do
